/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 .\public\model\BossChairOne.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const BossChairOne = (props)=> {
  const { nodes, materials } = useGLTF('model/BossChairOne.glb')
  return (
    <group {...props} dispose={null} position={[0,0,-12]}>
      <group position={[-0.738, 0.551, 9.719]}>
        <mesh geometry={nodes['Chair-Boss2-Material_#2863'].geometry} material={materials['Material #2863']} />
        <mesh geometry={nodes['Chair-Boss2-Material_#2863_1'].geometry} material={materials['Material #2863']} />
        <mesh geometry={nodes['Chair-Boss2-Material_#2865'].geometry} material={materials['Material #2865']} />
        <mesh geometry={nodes['Chair-Boss2-Material_#2862'].geometry} material={materials['Material #2862']} />
        <mesh geometry={nodes['Chair-Boss2-Material_#2862_1'].geometry} material={materials['Material #2862']} />
        <mesh geometry={nodes['Chair-Boss2-Material_#2862_2'].geometry} material={materials['Material #2862']} />
        <mesh geometry={nodes['Chair-Boss2-Material_#2862_3'].geometry} material={materials['Material #2862']} />
        <mesh geometry={nodes['Chair-Boss2-Material_#2863_2'].geometry} material={materials['Material #2863']} />
        <mesh geometry={nodes['Chair-Boss2-Material_#2102'].geometry} material={materials['Material #2102']} />
        <mesh geometry={nodes['Chair-Boss2-Mat4'].geometry} material={materials['Mat.4']} />
      </group>
    </group>
  )
}

useGLTF.preload('model/BossChairOne.glb')
export default BossChairOne