/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 .\public\model\porte.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Porte = (props)=> {
  const { nodes, materials } = useGLTF('model/porte.glb')
  // console.log(nodes.Office_1__coronaobj);
  return (
    <group {...props} dispose={null} scale={10}>
      <group position={[1.132, 0, 15.709]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.wire_088088225.geometry} material={materials.inox} castShadow receiveShadow/>
        <mesh geometry={nodes.wire_085028177.geometry} material={materials['bois-dark']} castShadow receiveShadow />
        <mesh geometry={nodes['wire_086086086-Mat16'].geometry} material={materials['bois-dark']} castShadow receiveShadow />
        <mesh geometry={nodes['wire_086086086-inox'].geometry} material={materials.inox} castShadow receiveShadow />
      </group>
    </group>
  )
}

useGLTF.preload('model/porte.glb')

export default Porte
